=== dzena/tuwien/bakk/SSD/SSD-FLO/firma-ns.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Dateiname: firma-ns.dtd -->
	
	<!-- FIRMA -->
	<!ELEMENT soft:firma (soft:team+, soft:projekt*)>
	<!ATTLIST soft:firma 
   				xmlns:soft CDATA #REQUIRED
				xmlns:xsi CDATA #REQUIRED
				xsi:noNamespaceSchemaLocation CDATA #REQUIRED
				name NMTOKEN #REQUIRED
   				nummer ID #FIXED 'e0604411'			
	> 
   
   	<!-- TEAM -->
	<!ELEMENT soft:team (soft:mitarbeiter, soft:mitarbeiter, soft:mitarbeiter*)>
	<!ATTLIST soft:team 
   				id ID #REQUIRED
	>
   	
	<!-- MITARBEITER -->
	<!ELEMENT soft:mitarbeiter (#PCDATA)>
	<!ATTLIST soft:mitarbeiter 
   				position (leiter | mitglied) 'mitglied'
	>
   
   
   	<!-- PROJEKT -->
	<!ELEMENT soft:projekt (soft:name, soft:beschreibung?)>
	<!ATTLIST soft:projekt 
   				team IDREF #REQUIRED
   				arbeitsstunden NMTOKEN #IMPLIED
	>
	
	<!-- SONSTIGE ELEMENTE -->
	<!ELEMENT soft:beschreibung (#PCDATA | soft:schlagwort)*>
	<!ELEMENT soft:name (#PCDATA)>
	<!ELEMENT soft:schlagwort (#PCDATA)>

=== dzena/tuwien/bakk/SSD/firma-ns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE firma SYSTEM "firma-ns.dtd" >

<soft:firma  xmlns:soft="http://www.dbai.tuwien.ac.at/software/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="firma-ns.xsd" 
    name="Favre-Bulle" nummer="e0426099">
    <soft:team id="team1">
        <soft:mitarbeiter>Peter Behrmann</soft:mitarbeiter>
        <soft:mitarbeiter position="leiter">Ingrid Thurnher</soft:mitarbeiter>
    </soft:team>
    <soft:team id="team2">
        <soft:mitarbeiter position="leiter">Christine</soft:mitarbeiter>
        <soft:mitarbeiter>Patrick</soft:mitarbeiter>
        <soft:mitarbeiter>Jack</soft:mitarbeiter>
        <soft:mitarbeiter>Jan</soft:mitarbeiter>
    </soft:team>
    
    <soft:projekt team="team1">
        <soft:name>Projekt 1</soft:name>
    </soft:projekt>
    
    <soft:projekt team="team2" arbeitsstunden="140">
        <soft:name>Projekt 2</soft:name>
        <soft:beschreibung>
            <soft:schlagwort>Wort1</soft:schlagwort>
            <soft:schlagwort>Wort2</soft:schlagwort>
            Noch ein bisschen Text
            <soft:schlagwort>Wort3</soft:schlagwort>
            Nochmal Text uns so wieter.
        </soft:beschreibung>
    </soft:projekt>
</soft:firma>
